apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-bootcamp1
  labels:
    app: kubernetes-bootcamp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-bootcamp1
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp1
    spec:
      containers:
      - name: kubernetes-bootcamp1
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      
  